# hash:sha256:891291d3fa238e6e58bcd010d61b62a7db0b2e09af0c4472c45a5b57896161ef
FROM registry.codeocean.com/codeocean/miniconda3:4.8.2-python3.8-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    impyute==0.0.8 \
    numpy==1.19.4 \
    pandas==0.25.3
